# Generated by Django 3.2.16 on 2023-11-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_post_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Количество комментариев'),
        ),
    ]
