# Generated by Django 3.2.16 on 2023-11-24 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_comment_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',), 'verbose_name': 'публикация', 'verbose_name_plural': 'Публикации'},
        ),
    ]
